<a href="https://colab.research.google.com/github/AmanSingh0909/Data-engineer-learning-from-linkedin/blob/main/Array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1 = np.array([5,4,8,9,7])
arr2 = np.array([1,2,3,4,10])

sum = arr1 + arr2
print(sum)

[ 6  6 11 13 17]


In [2]:
sum = arr1 - arr2
print(sum)

[ 4  2  5  5 -3]


In [3]:
sum = arr1 * arr2
print(sum)

[ 5  8 24 36 70]


In [4]:
sum = arr1 / arr2
print(sum)

[5.         2.         2.66666667 2.25       0.7       ]


In [5]:
mean = np.mean(arr1)
print(mean)

6.6
