<a href="https://colab.research.google.com/github/AmanSingh0909/Data-engineer-learning-from-linkedin/blob/main/Indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1 = np.array([10,20,30,40,50])

secondele = arr1[1]

print(secondele)

20


In [2]:
print(arr1[::-1])

[50 40 30 20 10]


In [3]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

ele = matrix[1,1]
print(ele)

5


In [4]:
row = matrix[1,:]
print(row)

[4 5 6]


In [ ]:
ele = matrix[1,1]
print(ele)

In [5]:
col = matrix[:,1]
print(col)

[2 5 8]


In [6]:
data = ([1,2,3, np.nan,5,6])

missing = np.isnan(data)
print(missing)

[False False False  True False False]


In [7]:
data_fill = np.nan_to_num(data, nan=0)
print(data_fill)

[1. 2. 3. 0. 5. 6.]
